repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
        exclude_types: [csv]
    -   id: remove-tabs
        exclude_types: [csv]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
    - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
#      args: [--unsafe]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
  - repo: https://github.com/psf/black
    rev: 22.3.0 # Cf env.yml, can be any tag/version in https://github.com/psf/black/tags
    hooks:
      - id: black
	language_version: python

  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
#        additional_dependencies: [flake8-typing-imports==1.10.0]
#        exclude: ^tests
