[tool.pytest.ini_options]
# https://docs.pytest.org/en/stable/customize.html
addopts = '''
-ra
--tb=line
-W error
--doctest-modules
'''
# -ra: show extra test summary [...] (a)ll except passed [...]
# --tb=style: traceback print mode (auto/long/short/line/native/no)
# -W: set which warnings to report, "error" turns matching warnings into exceptions

norecursedirs = [
  ".git",
  ".github",
  ".pytest_cache",
  ".ipynb_checkpoints",
  "__pycache__",
]

[tool.coverage.run]
# https://coverage.readthedocs.io/en/latest/config.html
branch = true
omit = [
  "tests/test*",
]

[tool.coverage.report]
show_missing = true

[tool.coverage.html]
directory = "htmlcov"

[tool.black]
# https://black.readthedocs.io/en/stable/pyproject_toml.html
line-length = 99
target-version = ['py310']
exclude = '''
(
  /(
      \.git
    | \.github
    | \.pytest_cache
    | \.ipynb_checkpoints
  )/
)
'''
