name: Dev build

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    # TODO need to check if this really works with conda that way
    # strategy:
    #   matrix:
    #     python-versions: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Other Github actions to setup conda, not sure which is the best one:
      #    https://github.com/marketplace/actions/setup-miniconda
      #      --> seems to work fine
      #    https://github.com/matthewrmshin/conda-action
      #      --> No success, how to activate env? Has only 2 stars...
      #    https://github.com/marketplace/actions/setup-conda
      #      --> not tested yet
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if env.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          # python-version: 3.9
          mamba-version: "*"
          activate-environment: syfop
          channels: conda-forge
          channel-priority: strict
          environment-file: env.yml
          # TODO does this cause troubles with finding packages?
          # https://github.com/conda-incubator/setup-miniconda/issues/267
          # use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Run unit tests (skip the ones with Gurobi)
        run: python -m pytest -k "not gurobi" tests
